# Midterm 1: run the data generator in Colab

Use this notebook if you cannot run Python or git on your own machine. It only **generates and shows your data**. You write your answers in `ANSWERS.md` on **your fork on github.com** (open the file, click the pencil icon, edit, *Commit changes*), then submit the commit URL in Canvas. See the README for the rules.

1. Fill in `GITHUB_USERNAME` (the account that owns your fork) and `CODE` (`PRACTICE` to rehearse; the real code is on the board during the exam).
2. Run the three code cells in order.

In [5]:
GITHUB_USERNAME = "aibergeniskendirov-hub"   # e.g. "aigerim-k"
CODE = "ZEBRA-28"      # replace with the session code during the exam
assert GITHUB_USERNAME, "fill in GITHUB_USERNAME first"

In [6]:
import os

if not os.path.exists("midterm-1-AI-course"):
    !git clone --quiet https://github.com/unreal-kz/midterm-1-AI-course.git
%cd midterm-1-AI-course
!python make_my_data.py --github {GITHUB_USERNAME} --code {CODE}

/content/midterm-1-AI-course/midterm-1-AI-course
Wrote 3 files to my_data/ · fingerprint 83b3806f
Next: open my_data/DATA.md

In [7]:
import pandas as pd
from IPython.display import Markdown, display

display(Markdown(open("my_data/DATA.md", encoding="utf-8").read()))
ranks = pd.read_csv("my_data/retrieval_ranks.csv")   # Part 1
docs = pd.read_csv("my_data/doc_results.csv")        # Part 2
display(ranks.head(), docs)

# Midterm 1: your data

GitHub username: `aibergeniskendirov-hub` · session code: `zebra-28` · generator v1

**Fingerprint: `83b3806f`**: copy it into the first lines of `ANSWERS.md`. All numbers below are synthetic: this is an exam, not a measurement.

## Part 1: inputs

`retrieval_ranks.csv`: 60 test questions (20 EN, 20 RU, 20 KK). `rank_A` and `rank_B` give the position of the correct chunk in the top 10 retrieved under config A and config B; **11 means the correct chunk was not in the top 10.**

Production traffic and Model M token counts (tokens per item, as counted by Model M's tokenizer):

| language | share of traffic | question tokens | answer tokens | chunk A tokens | chunk B tokens |
|---|---|---|---|---|---|
| EN | 56 % | 26 | 127 | 275 | 67 |
| RU | 27 % | 43 | 208 | 451 | 110 |
| KK | 17 % | 50 | 244 | 528 | 129 |

- Requests per day: **12,000**, in the traffic shares above.
- System prompt: **278** tokens in every request.
- Price: **$1** per million input tokens, **$6** per million output tokens.
- Annual budget for this service (model calls only): **$12,200**.

## Part 2: inputs

`doc_results.csv`: for each pipeline, language and scan condition, `n_docs` test invoices and `n_correct` = invoices whose number, date, seller ID and total were all extracted exactly (strict scorer, as in Lab 04).

- **Pipeline H**: hosted vision-language API in a data centre abroad, pay per token; each page is sent as an image.
- **Pipeline L**: open vision-language model on your own server in Kazakhstan, fixed monthly cost.

- Volume: **3,000** scanned pages per day. In **23 %** of them an individual's name and ИИН are printed (sole proprietors, receipts).
- Page image: **1654 × 2339** pixels. Pipeline H counts an image as ⌈width ÷ 28⌉ × ⌈height ÷ 28⌉ input tokens and returns about **371** output tokens per page (the JSON).
- Pipeline H price: **$1** per million input tokens, **$5** per million output tokens.
- Pipeline L: one server costs **$450** per month and handles up to **6,000** pages per day; add servers as needed.

## Part 3: your five questions

Answer each in `ANSWERS.md`: one **Number** line and one **Why** line of at most 40 words.

### Q1

The same support request, once in English and once in Kazakh, through Model M ($3 per million input tokens, $18 per million output tokens):

| | input tokens | output tokens |
|---|---|---|
| EN | 1,176 | 129 |
| KK | 2,731 | 225 |

Compute the token ratio (total tokens KK ÷ EN) and the bill ratio (cost KK ÷ cost EN). **Number:** the bill ratio (2 decimals). **Why** (at most 40 words): why is the bill ratio not equal to the token ratio?

### Q2

A teammate sets the chunk size to **576 tokens, counted with cl100k**. The retrieval model (e5-small) reads at most 512 of *its own* tokens. Assume e5 tokens grow in proportion to cl100k tokens at the rate measured in Lecture 4.1 (a chunker told 256 cl100k tokens produced chunks of 263 / 128 / 76 e5 tokens for EN / RU / KK), and that every chunk is exactly the full size.

In an English chunk, the sentence that contains the answer starts 75 % of the way into the chunk and is shorter than 20 e5 tokens. **Number:** the position of the start of that sentence, in e5 tokens (nearest integer). **Why** (at most 40 words): can a question that matches only that sentence retrieve this chunk, and would you see an error?

### Q3

A language model gives these next-token scores for the prompt "The branch is closed on":

| token | score |
|---|---|
| Monday | 4.9 |
| Friday | 4.0 |
| Sunday | 3.3 |
| holiday | 2.1 |
| Easter | 1.2 |

Use temperature T = 1, then apply top-p = 0.95. **Number:** the probability of the top token after top-p and renormalisation, in percent (1 decimal). **Why** (at most 40 words): how does top-p differ from lowering the temperature?

### Q4

Two models answer the same 100 factual questions (1 point per correct answer on the public leaderboard):

| | correct | wrong | "I don't know" |
|---|---|---|---|
| Model X | 69 | 31 | 0 |
| Model Y | 66 | 15 | 19 |

Now score them again with a penalty: +1 per correct answer, −1 per wrong answer, 0 for "I don't know". **Number:** Y's penalised score minus X's (negative if X is ahead). **Why** (at most 40 words): which model does the public leaderboard prefer, and what does that teach a model to do?

### Q5

A lab trains a model with **70 billion parameters on 19.53 trillion tokens**. Chinchilla (Lecture 1.1) trained 70 billion parameters on 1.4 trillion tokens, which the paper presents as the compute-optimal ratio. **Number:** this model's tokens per parameter divided by Chinchilla's tokens per parameter (2 decimals). **Why** (at most 40 words): is the model under- or over-trained by that criterion, and what did Chinchilla say about models such as GPT-3?

   qid lang  rank_A  rank_B
0  q01   RU       3      11
1  q02   RU       1       2
2  q03   RU       3      11
3  q04   RU       2      11
4  q05   KK       1       3

   pipeline lang condition  n_docs  n_correct
0         H   EN     clean      30         29
1         H   EN  degraded      30         26
2         H   RU     clean      30         28
3         H   RU  degraded      30         25
4         H   KK     clean      30         23
5         H   KK  degraded      30         25
6         L   EN     clean      30         27
7         L   EN  degraded      30         24
8         L   RU     clean      30         26
9         L   RU  degraded      30         23
10        L   KK     clean      30         24
11        L   KK  degraded      30         23

In [8]:
display(ranks)

for config in ["A", "B"]:
    column = "rank_" + config

    for k in [1, 3, 5]:
        hits = (ranks[column] <= k).sum()
        recall = hits / len(ranks)

        print(config, "k =", k, "найдено:", hits, "recall:", recall)

    qid lang  rank_A  rank_B
0   q01   RU       3      11
1   q02   RU       1       2
2   q03   RU       3      11
3   q04   RU       2      11
4   q05   KK       1       3
5   q06   KK       1       1
6   q07   EN       1       1
7   q08   KK       1       5
8   q09   KK       3       7
9   q10   EN       1       1
10  q11   RU       1       2
11  q12   EN       1       1
12  q13   KK       1       3
13  q14   RU       1       4
14  q15   EN       1      11
15  q16   RU       1       1
16  q17   RU       1       1
17  q18   KK       5      11
18  q19   EN       1       9
19  q20   EN       2       5
20  q21   KK       1       2
21  q22   EN       1       1
22  q23   EN       1       4
23  q24   EN       1       4
24  q25   EN       1       3
25  q26   RU      11      11
26  q27   RU       1       1
27  q28   EN       1       3
28  q29   KK       1       1
29  q30   RU       1       1
30  q31   RU       1       1
31  q32   RU       1       1
32  q33   KK       3       5
33  q34   KK      11      11
34  q35   EN       1       4
35  q36   KK       1       2
36  q37   RU       1       4
37  q38   EN      11      11
38  q39   KK       2      11
39  q40   EN       1       2
40  q41   KK       1       2
41  q42   EN       1       3
42  q43   RU       1       1
43  q44   KK       1      11
44  q45   RU      11      11
45  q46   KK       2      11
46  q47   RU       5      11
47  q48   RU       1      11
48  q49   RU       9      11
49  q50   KK       2      11
50  q51   KK       1       1
51  q52   KK       1       4
52  q53   RU       1       1
53  q54   EN       1       2
54  q55   KK       1      11
55  q56   EN       1       1
56  q57   EN       1       7
57  q58   KK       4      11
58  q59   EN       2      11
59  q60   EN      10      11

A k = 1 найдено: 41 recall: 0.6833333333333333
A k = 3 найдено: 51 recall: 0.85
A k = 5 найдено: 54 recall: 0.9
B k = 1 найдено: 16 recall: 0.26666666666666666
B k = 3 найдено: 28 recall: 0.4666666666666667
B k = 5 найдено: 37 recall: 0.6166666666666667

In [9]:
for config in ["A", "B"]:
    total = 0

    for rank in ranks["rank_" + config]:
        if rank <= 10:
            total += 1 / rank

    mrr = total / len(ranks)
    print(config, "MRR@10 =", round(mrr, 6))

A MRR@10 = 0.769907
B MRR@10 = 0.394392

In [10]:
import math

def wilson(hits, n):
    p = hits / n
    z = 1.96

    denominator = 1 + z**2 / n
    centre = (p + z**2 / (2 * n)) / denominator
    half = z * math.sqrt(
        p * (1 - p) / n + z**2 / (4 * n**2)
    ) / denominator

    return centre - half, centre + half

for config in ["A", "B"]:
    for k in [3, 5]:
        hits = (ranks["rank_" + config] <= k).sum()
        n = len(ranks)
        lower, upper = wilson(hits, n)

        print(
            f"{config}, k={k}: "
            f"recall={hits / n:.2%}, "
            f"lower={lower:.2%}, upper={upper:.2%}"
        )

A, k=3: recall=85.00%, lower=73.89%, upper=91.90%
A, k=5: recall=90.00%, lower=79.85%, upper=95.34%
B, k=3: recall=46.67%, lower=34.63%, upper=59.11%
B, k=5: recall=61.67%, lower=49.02%, upper=72.91%

In [11]:
languages = [
    ("EN", 0.56, 26, 127, 275, 67),
    ("RU", 0.27, 43, 208, 451, 110),
    ("KK", 0.17, 50, 244, 528, 129)
]

for config in ["A", "B"]:
    for k in [3, 5]:
        average_cost = 0

        for lang, share, question, answer, chunk_a, chunk_b in languages:
            chunk = chunk_a if config == "A" else chunk_b
            input_tokens = 278 + question + k * chunk

            request_cost = (input_tokens * 1 + answer * 6) / 1000000
            average_cost += share * request_cost

        annual_cost = average_cost * 12000 * 365
        print(f"{config}, k={k}: {annual_cost:.2f} USD")

A, k=3: 10607.57 USD
A, k=5: 13809.61 USD
B, k=3: 6975.94 USD
B, k=5: 7756.89 USD

In [3]:
import pandas as pd
from pathlib import Path

paths = list(Path("/content").rglob("retrieval_ranks.csv"))

print("Найденные файлы:", paths)

Найденные файлы: []

In [ ]:
from google.colab import files
import pandas as pd
import io

uploaded = files.upload()

`ranks` and `docs` are ready for you to compute with. Remember the **fingerprint** at the top of the data sheet: it goes into the first lines of `ANSWERS.md`.